embedding_size: 64
n_layers: 4
reg_weight: 1e-04
require_pow: True
gate_layer_ids: [2, 3]
gating_mlp_dims: [64, 16, 2]
dropout_ratio: 0.2

warm_up_epochs: 50
ori_temp: 0.7
min_temp: 0.01
gum_temp_decay: 0.005
epoch_temp_decay: 1

# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
NEG_PREFIX: neg_
LABEL_FIELD: label

load_col:
  inter: [ user_id, item_id ]
ITEM_ID_FIELD: item_id

# training and evaluation
epochs: 500
train_batch_size: 4096
valid_metric: MRR@10
eval_batch_size: 4096000
learning_rate: 0.002
activation_function: leakyrelu

topk: [10, 20, 50]
user_inter_num_interval: "[15,inf)"
item_inter_num_interval: "[15,inf)"
