type: "ED"
n_layers: 3

field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
NEG_PREFIX: neg_
LABEL_FIELD: label
load_col:
    inter: [user_id, item_id, rating]
val_interval:
    rating: "[3,inf)"
unused_col:
    inter: [rating]

epochs: 500
train_batch_size: 4096
valid_metric: MRR@10
eval_batch_size: 4096000

# ml-1m
ssl_tau: 0.5
reg_weight: 1e-4
ssl_weight: 0.005
drop_ratio: 0.1
embedding_size: 64
learning_rate: 0.002
topk: [10, 20, 50]

#
## SGL
#ssl_tau: 0.2
#reg_weight: 1e-4
#ssl_weight: 0.005
#drop_ratio: 0.1.txt
#embedding_size: 64
#learning_rate: 0.001
#
#epochs: 500
#train_batch_size: 2048
#valid_metric: MRR@10
#eval_batch_size: 4096
#
#load_col:
#  inter: [ user_id, business_id, stars ]
#ITEM_ID_FIELD: business_id
#RATING_FIELD: stars
#
#user_inter_num_interval: "[25,inf)"
#item_inter_num_interval: "[25,inf)"
#val_interval:
#  stars: "[3,inf)"


# amazon books
#ssl_tau: 0.2
#reg_weight: 1e-4
#ssl_weight: 0.005
#drop_ratio: 0.1.txt
#embedding_size: 64
#learning_rate: 0.001
#
#epochs: 500
#train_batch_size: 2048
#valid_metric: MRR@10
#eval_batch_size: 4096
#
#ITEM_ID_FIELD: item_id
#RATING_FIELD: rating
#load_col:
#    inter: [user_id, item_id, rating]
#unused_col:
#    inter: [rating]
#
#user_inter_num_interval: "[20,inf)"
#item_inter_num_interval: "[20,inf)"
#val_interval:
#     rating: "[3,inf)"

#ssl_tau: 0.2
#reg_weight: 1e-4
#ssl_weight: 0.005
#drop_ratio: 0.1.txt
#embedding_size: 64
#learning_rate: 0.001
#
#epochs: 500
#train_batch_size: 4096
#
#valid_metric: MRR@10
#eval_batch_size: 4096000
#
#ITEM_ID_FIELD: item_id
#RATING_FIELD: rating
#load_col:
#    inter: [user_id, item_id]
#
#user_inter_num_interval: "[15,inf)"
#item_inter_num_interval: "[15,inf)"
#
#topk: [10, 20, 50]
