load_col:
  inter: [user_id, item_id]

#user_inter_num_interval: "[15,inf)"
#item_inter_num_interval: "[15,inf)"

learning_rate: 0.002
reg_weight: 0.0001
n_layers: 2
lambda: 1e-5
eps: 0.1
temperature: 0.05

embedding_size: 64

field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
NEG_PREFIX: neg_
LABEL_FIELD: label

# training and evaluation
epochs: 500
train_batch_size: 4096
valid_metric: MRR@10
eval_batch_size: 4096000